baseURL = 'https://donald30498.github.io/DD/'
languageCode = 'UTF-8'
title = 'Donald30498'
theme = "beautifulhugo"

[Author]
  name = "Donald Wu"
  website = "https://donald30498.github.io/DD/"
  email = "donald30498@outlook.com"
  github = "Donald30498"
  twitter = "loseritersenior"
  stackoverflow = "https://stackoverflow.com/users/15233288/shalanes"