baseURL = 'https://donald30498.github.io/DD/'
languageCode = 'UTF-8'
title = 'Donald30498'
theme = "beautifulhugo"

[[social_icons]]
id = "email"
url = "mailto:donald30498@outlook.com"
title = "Email me"
icon = "fas fa-envelope"